// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Repository.Data;

#nullable disable

namespace Repository.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260927114824_Start400Pts")]
    partial class Start400Pts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Models.ApiRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("FromPlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("from_player_id");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid")
                        .HasColumnName("game_id");

                    b.Property<bool>("IsSent")
                        .HasColumnType("boolean")
                        .HasColumnName("is_sent");

                    b.Property<string>("PieceUid")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("piece_uid");

                    b.Property<DateTime>("RequestTs")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("request_ts");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.Property<short>("X")
                        .HasColumnType("smallint")
                        .HasColumnName("x");

                    b.Property<short>("Y")
                        .HasColumnType("smallint")
                        .HasColumnName("y");

                    b.HasKey("Id")
                        .HasName("pk_api_request");

                    b.HasIndex("FromPlayerId")
                        .HasDatabaseName("ix_api_request_from_player_id");

                    b.HasIndex("GameId", "PieceUid")
                        .HasDatabaseName("ix_api_request_game_id_piece_uid");

                    b.ToTable("API_REQUEST", (string)null);
                });

            modelBuilder.Entity("Domain.Models.ApiResponse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ApiRequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("api_request_id");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.HasKey("Id")
                        .HasName("pk_api_response");

                    b.HasIndex("ApiRequestId")
                        .IsUnique()
                        .HasDatabaseName("ix_api_response_api_request_id");

                    b.ToTable("API_RESPONSE", (string)null);
                });

            modelBuilder.Entity("Domain.Models.Block", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BlockedId")
                        .HasColumnType("uuid")
                        .HasColumnName("blocked_id");

                    b.Property<Guid>("BlockerId")
                        .HasColumnType("uuid")
                        .HasColumnName("blocker_id");

                    b.Property<DateTime?>("EndTs")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_ts");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTime>("StartTs")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_ts");

                    b.HasKey("Id")
                        .HasName("pk_block");

                    b.HasIndex("BlockedId")
                        .HasDatabaseName("ix_block_blocked_id");

                    b.HasIndex("BlockerId")
                        .HasDatabaseName("ix_block_blocker_id");

                    b.ToTable("BLOCK", (string)null);
                });

            modelBuilder.Entity("Domain.Models.Friendship", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("EndTs")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_ts");

                    b.Property<Guid>("Friend1Id")
                        .HasColumnType("uuid")
                        .HasColumnName("friend1_id");

                    b.Property<Guid>("Friend2Id")
                        .HasColumnType("uuid")
                        .HasColumnName("friend2_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTime>("StartTs")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_ts");

                    b.HasKey("Id")
                        .HasName("pk_friendship");

                    b.HasIndex("Friend1Id")
                        .HasDatabaseName("ix_friendship_friend1id");

                    b.HasIndex("Friend2Id")
                        .HasDatabaseName("ix_friendship_friend2id");

                    b.ToTable("FRIENDSHIP", (string)null);
                });

            modelBuilder.Entity("Domain.Models.FriendshipRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("EndTs")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_ts");

                    b.Property<bool?>("IsAccepted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_accepted");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<Guid>("ReceiverId")
                        .HasColumnType("uuid")
                        .HasColumnName("receiver_id");

                    b.Property<DateTime>("RequestTs")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("request_ts");

                    b.Property<Guid>("RequesterId")
                        .HasColumnType("uuid")
                        .HasColumnName("requester_id");

                    b.Property<DateTime>("StartTs")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_ts");

                    b.HasKey("Id")
                        .HasName("pk_friendship_request");

                    b.HasIndex("ReceiverId")
                        .HasDatabaseName("ix_friendship_request_receiver_id");

                    b.HasIndex("RequesterId")
                        .HasDatabaseName("ix_friendship_request_requester_id");

                    b.ToTable("FRIENDSHIP_REQUEST", (string)null);
                });

            modelBuilder.Entity("Domain.Models.Game", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("EndTs")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_ts");

                    b.Property<Guid>("GameRequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("game_request_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool?>("IsDraw")
                        .HasColumnType("boolean")
                        .HasColumnName("is_draw");

                    b.Property<bool>("IsPvp")
                        .HasColumnType("boolean")
                        .HasColumnName("is_pvp");

                    b.Property<bool>("IsWhiteOnTurn")
                        .HasColumnType("boolean")
                        .HasColumnName("is_white_on_turn");

                    b.Property<bool?>("IsWhiteWinner")
                        .HasColumnType("boolean")
                        .HasColumnName("is_white_winner");

                    b.Property<DateTime>("StartTs")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_ts");

                    b.HasKey("Id")
                        .HasName("pk_game");

                    b.HasIndex("GameRequestId")
                        .IsUnique()
                        .HasDatabaseName("ix_game_game_request_id");

                    b.ToTable("GAME", (string)null);
                });

            modelBuilder.Entity("Domain.Models.GameRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("EndTs")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_ts");

                    b.Property<bool?>("IsAccepted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_accepted");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsPvpRequest")
                        .HasColumnType("boolean")
                        .HasColumnName("is_pvp_request");

                    b.Property<Guid?>("ReceiverId")
                        .HasColumnType("uuid")
                        .HasColumnName("receiver_id");

                    b.Property<Guid>("RequesterId")
                        .HasColumnType("uuid")
                        .HasColumnName("requester_id");

                    b.Property<DateTime>("StartTs")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_ts");

                    b.HasKey("Id")
                        .HasName("pk_game_request");

                    b.HasIndex("ReceiverId")
                        .HasDatabaseName("ix_game_request_receiver_id");

                    b.HasIndex("RequesterId")
                        .HasDatabaseName("ix_game_request_requester_id");

                    b.ToTable("GAME_REQUEST", (string)null);
                });

            modelBuilder.Entity("Domain.Models.Piece", b =>
                {
                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid")
                        .HasColumnName("game_id");

                    b.Property<string>("PieceUid")
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("piece_uid");

                    b.Property<bool>("IsWhite")
                        .HasColumnType("boolean")
                        .HasColumnName("is_white");

                    b.Property<short>("PieceType")
                        .HasColumnType("smallint")
                        .HasColumnName("piece_type");

                    b.Property<short>("X")
                        .HasColumnType("smallint")
                        .HasColumnName("x");

                    b.Property<short>("Y")
                        .HasColumnType("smallint")
                        .HasColumnName("y");

                    b.HasKey("GameId", "PieceUid")
                        .HasName("pk_piece");

                    b.ToTable("PIECE", (string)null);
                });

            modelBuilder.Entity("Domain.Models.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer")
                        .HasColumnName("access_failed_count");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("email_confirmed");

                    b.Property<bool>("IsInGame")
                        .HasColumnType("boolean")
                        .HasColumnName("is_in_game");

                    b.Property<bool>("IsOnline")
                        .HasColumnType("boolean")
                        .HasColumnName("is_online");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("lockout_enabled");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockout_end");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_user_name");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("phone_number_confirmed");

                    b.Property<int>("Points")
                        .HasColumnType("integer")
                        .HasColumnName("points");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text")
                        .HasColumnName("security_stamp");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("two_factor_enabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("user_name");

                    b.HasKey("Id")
                        .HasName("pk_player");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("PLAYER", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_name");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_roles");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_role_claims");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_asp_net_role_claims_role_id");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_user_claims");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_asp_net_user_claims_user_id");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text")
                        .HasColumnName("provider_key");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text")
                        .HasColumnName("provider_display_name");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("LoginProvider", "ProviderKey")
                        .HasName("pk_asp_net_user_logins");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_asp_net_user_logins_user_id");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId")
                        .HasName("pk_asp_net_user_roles");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_asp_net_user_roles_role_id");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("UserId", "LoginProvider", "Name")
                        .HasName("pk_asp_net_user_tokens");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Domain.Models.ApiRequest", b =>
                {
                    b.HasOne("Domain.Models.Player", "FromPlayer")
                        .WithMany()
                        .HasForeignKey("FromPlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_api_request_player_from_player_id");

                    b.HasOne("Domain.Models.Game", "Game")
                        .WithMany("ApiRequests")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_api_request_game_game_id");

                    b.HasOne("Domain.Models.Piece", "Piece")
                        .WithMany()
                        .HasForeignKey("GameId", "PieceUid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_api_request_piece_game_id_piece_uid");

                    b.Navigation("FromPlayer");

                    b.Navigation("Game");

                    b.Navigation("Piece");
                });

            modelBuilder.Entity("Domain.Models.ApiResponse", b =>
                {
                    b.HasOne("Domain.Models.ApiRequest", "ApiRequest")
                        .WithOne("ApiResponse")
                        .HasForeignKey("Domain.Models.ApiResponse", "ApiRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_api_response_api_request_api_request_id");

                    b.Navigation("ApiRequest");
                });

            modelBuilder.Entity("Domain.Models.Block", b =>
                {
                    b.HasOne("Domain.Models.Player", "Blocked")
                        .WithMany("BlockedByUsers")
                        .HasForeignKey("BlockedId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_block_player_blocked_id");

                    b.HasOne("Domain.Models.Player", "Blocker")
                        .WithMany("BlockedUsers")
                        .HasForeignKey("BlockerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_block_player_blocker_id");

                    b.Navigation("Blocked");

                    b.Navigation("Blocker");
                });

            modelBuilder.Entity("Domain.Models.Friendship", b =>
                {
                    b.HasOne("Domain.Models.Player", "Friend1")
                        .WithMany()
                        .HasForeignKey("Friend1Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_friendship_player_friend1id");

                    b.HasOne("Domain.Models.Player", "Friend2")
                        .WithMany()
                        .HasForeignKey("Friend2Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_friendship_player_friend2id");

                    b.Navigation("Friend1");

                    b.Navigation("Friend2");
                });

            modelBuilder.Entity("Domain.Models.FriendshipRequest", b =>
                {
                    b.HasOne("Domain.Models.Player", "Receiver")
                        .WithMany("ReceivedFriendRequests")
                        .HasForeignKey("ReceiverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_friendship_request_player_receiver_id");

                    b.HasOne("Domain.Models.Player", "Requester")
                        .WithMany("SentFriendRequests")
                        .HasForeignKey("RequesterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_friendship_request_player_requester_id");

                    b.Navigation("Receiver");

                    b.Navigation("Requester");
                });

            modelBuilder.Entity("Domain.Models.Game", b =>
                {
                    b.HasOne("Domain.Models.GameRequest", "GameRequest")
                        .WithOne("Game")
                        .HasForeignKey("Domain.Models.Game", "GameRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_game_game_request_game_request_id");

                    b.Navigation("GameRequest");
                });

            modelBuilder.Entity("Domain.Models.GameRequest", b =>
                {
                    b.HasOne("Domain.Models.Player", "Receiver")
                        .WithMany()
                        .HasForeignKey("ReceiverId")
                        .HasConstraintName("fk_game_request_player_receiver_id");

                    b.HasOne("Domain.Models.Player", "Requester")
                        .WithMany()
                        .HasForeignKey("RequesterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_game_request_player_requester_id");

                    b.Navigation("Receiver");

                    b.Navigation("Requester");
                });

            modelBuilder.Entity("Domain.Models.Piece", b =>
                {
                    b.HasOne("Domain.Models.Game", "Game")
                        .WithMany("Pieces")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_piece_game_game_id");

                    b.Navigation("Game");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_role_claims_asp_net_roles_role_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("Domain.Models.Player", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_claims_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("Domain.Models.Player", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_logins_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_roles_asp_net_roles_role_id");

                    b.HasOne("Domain.Models.Player", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_roles_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("Domain.Models.Player", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_tokens_asp_net_users_user_id");
                });

            modelBuilder.Entity("Domain.Models.ApiRequest", b =>
                {
                    b.Navigation("ApiResponse")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Models.Game", b =>
                {
                    b.Navigation("ApiRequests");

                    b.Navigation("Pieces");
                });

            modelBuilder.Entity("Domain.Models.GameRequest", b =>
                {
                    b.Navigation("Game")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Models.Player", b =>
                {
                    b.Navigation("BlockedByUsers");

                    b.Navigation("BlockedUsers");

                    b.Navigation("ReceivedFriendRequests");

                    b.Navigation("SentFriendRequests");
                });
#pragma warning restore 612, 618
        }
    }
}
